# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 217ba27d4bb9057334cfa1916db7f13d1e9283c667ff97d72ef12b66cbf83aaab7e0e88e841766ccaf231d5741e6ea92c8a829f2b1b4c69aae166ae351876af0

test:
  secret_key_base: 73cf0e13701e5ad41220753e6196d32840583dafe2a6ad85edd8f57db952e6ea8ca52b607dcfc2d8ce8d3d3aa8af98195276449d0f9e02b656a65351a699904e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
